# SPDX-License-Identifier: MIT
# Copyright (c) 2026 John Chapman
"""Guided first-run setup: probe the installed CLIs and scaffold a starter config and panel.

Both the ``setup`` MCP tool and the ``rutherford-mcp-server init`` CLI build the same
:class:`SetupPlan` from this module: a snapshot of which CLIs are ready, a recommended starter
panel built from them, and the exact files to write (the main ``config.toml`` and a starter
``panels.toon``). Building the plan is pure -- it computes file contents and target paths but does
not touch disk -- so a caller can show it before applying. :func:`apply_setup_plan` writes it, never
overwriting an existing file unless asked.
"""

from __future__ import annotations

from collections.abc import Iterable, Mapping
from pathlib import Path
from typing import Any

from pydantic import BaseModel, Field

from ..config.loader import default_global_config_path
from ..config.locations import CONFIG_DIRNAME, home_dir
from ..domain.enums import AuthState
from ..domain.models import AdapterStatus
from ..io.serialize import encode

#: Auth states that count as "ready to use" -- authenticated, or unknown (verified live by doctor).
_READY_AUTH = (AuthState.AUTHENTICATED, AuthState.UNKNOWN)


class ProposedFile(BaseModel):
    """A file setup would write: its path, format, full content, and whether it already exists."""

    path: str
    kind: str
    format: str
    content: str
    exists: bool


class DetectedCli(BaseModel):
    """A one-line snapshot of one CLI for the setup summary."""

    id: str
    installed: bool
    auth: AuthState
    ready: bool


class SetupPlan(BaseModel):
    """The proposed setup: what was detected, the recommended panel, and the files to write."""

    detected: list[DetectedCli] = Field(default_factory=list)
    recommended_panel: list[str] = Field(default_factory=list)
    files: list[ProposedFile] = Field(default_factory=list)
    notes: list[str] = Field(default_factory=list)


def build_setup_plan(
    statuses: Iterable[AdapterStatus],
    *,
    env: Mapping[str, str],
    safety_mode: str = "read_only",
    trusted_workspaces: Iterable[str] = (),
    panel_name: str = "default",
    ollama_model: str | None = None,
    configure_ollama: bool = True,
) -> SetupPlan:
    """Build a :class:`SetupPlan` from probed adapter statuses, without touching disk.

    A CLI is "ready" when it is installed and either authenticated or auth-unknown (the optimistic
    case doctor verifies live). The starter panel is the ready CLIs, proposed only when at least two
    are ready. The config carries the chosen default safety mode and any trusted workspaces.
    ``ollama_model`` is the user's chosen default Ollama model; when it is unset or not installed, a
    coding model is preferred from what is installed. ``configure_ollama=False`` skips setting any
    Ollama default (the wizard's "skip" choice), leaving the model to be named per call.
    """
    statuses = list(statuses)
    detected: list[DetectedCli] = []
    ready: list[str] = []
    panel_eligible: list[str] = []  # ready and not optional -- an opt-in local model is not auto-added
    for status in statuses:
        is_ready = status.installed and status.auth.state in _READY_AUTH
        detected.append(DetectedCli(id=status.id, installed=status.installed, auth=status.auth.state, ready=is_ready))
        if is_ready:
            ready.append(status.id)
            if not status.optional:
                panel_eligible.append(status.id)

    files: list[ProposedFile] = []
    notes: list[str] = []

    config: dict[str, Any] = {"default_safety_mode": safety_mode}
    workspaces = [path for path in trusted_workspaces if path]
    if workspaces:
        config["trusted_workspaces"] = workspaces
    config_path = default_global_config_path(env)
    content = "# Rutherford configuration (generated by setup)\n" + _to_toml(config)

    # Set the local model's default from what is installed (Ollama is optional and has no built-in
    # default). ``ollama_model`` is the user's interactive choice; otherwise prefer a coding model.
    # ``configure_ollama=False`` is the wizard's "skip" -- leave the model to be named per call.
    ollama_models = _ollama_models(statuses)
    if ollama_models and configure_ollama:
        chosen = ollama_model if ollama_model in ollama_models else _prefer_coder(ollama_models)
        others = [m for m in ollama_models if m != chosen]
        content += f"\n[adapters.ollama]\ndefault_model = {_toml_string(chosen)}\n"
        note = (
            f"Ollama default model set to {chosen!r}. To change it later: run `ollama list` to see "
            f"your models, then edit the `[adapters.ollama] default_model` line in {config_path} -- "
            "or re-run `rutherford-mcp-server init --force` and pick a different one."
        )
        if others:
            note += f" Other installed models: {', '.join(others)}."
        notes.append(note)
    elif ollama_models:
        notes.append(
            "Ollama is installed but no default model was set. Name a model per call with `model=`, "
            "or run `rutherford-mcp-server init --force` to set a default."
        )

    files.append(
        ProposedFile(
            path=str(config_path),
            kind="config",
            format="toml",
            content=content,
            exists=config_path.exists(),
        )
    )

    recommended: list[str] = []
    if len(panel_eligible) >= 2:
        recommended = panel_eligible
        panel = {
            "panels": {
                panel_name: {
                    "description": "Starter panel across your ready CLIs",
                    "targets": [{"cli": cli_id} for cli_id in panel_eligible],
                }
            }
        }
        panels_path = home_dir(env) / CONFIG_DIRNAME / "panels.toon"
        files.append(
            ProposedFile(
                path=str(panels_path),
                kind="panels",
                format="toon",
                content=encode(panel),
                exists=panels_path.exists(),
            )
        )
    else:
        notes.append(
            "Fewer than two CLIs are ready, so no starter panel was proposed. Sign in to more CLIs "
            "(see doctor) and re-run setup."
        )

    return SetupPlan(detected=detected, recommended_panel=recommended, files=files, notes=notes)


def apply_setup_plan(plan: SetupPlan, *, force: bool = False) -> list[str]:
    """Write the plan's files and return the paths written. Skips a file that already exists.

    An existing file is left untouched unless ``force`` is set, so setup never clobbers a config or
    panel you have already edited.
    """
    written: list[str] = []
    for proposed in plan.files:
        path = Path(proposed.path)
        if path.exists() and not force:
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(proposed.content, encoding="utf-8")
        written.append(proposed.path)
    return written


def format_plan_summary(plan: SetupPlan) -> str:
    """Render a human-readable summary of a plan for the CLI wizard."""
    lines = ["Detected CLIs:"]
    for cli in plan.detected:
        mark = "ready" if cli.ready else ("installed" if cli.installed else "not installed")
        lines.append(f"  - {cli.id}: {mark} (auth: {cli.auth.value})")
    if plan.recommended_panel:
        lines.append(f"\nStarter panel '{', '.join(plan.recommended_panel)}'.")
    for note in plan.notes:
        lines.append(f"\nNote: {note}")
    lines.append("\nFiles to write:")
    for proposed in plan.files:
        state = "exists -- will skip unless --force" if proposed.exists else "new"
        lines.append(f"  - {proposed.path} ({proposed.format}, {state})")
    return "\n".join(lines)


def _ollama_models(statuses: Iterable[AdapterStatus]) -> list[str]:
    """The Ollama adapter's installed models (from already-probed status), or empty if absent/none.

    Operates only on :class:`AdapterStatus` data, so it is OS-independent and unit-testable without a
    real Ollama.
    """
    for status in statuses:
        if status.id == "ollama" and status.installed:
            return list(status.models)
    return []


def _prefer_coder(models: list[str]) -> str:
    """Pick a sensible default from installed models: prefer a coding model, else the first."""
    return next((m for m in models if "coder" in m.lower() or "code" in m.lower()), models[0])


def _to_toml(data: Mapping[str, Any]) -> str:
    """Render a flat config mapping to TOML. Handles the scalar and string-list shapes setup emits."""
    lines: list[str] = []
    for key, value in data.items():
        if isinstance(value, bool):
            lines.append(f"{key} = {str(value).lower()}")
        elif isinstance(value, (int, float)):
            lines.append(f"{key} = {value}")
        elif isinstance(value, str):
            lines.append(f"{key} = {_toml_string(value)}")
        elif isinstance(value, list):
            rendered = ", ".join(_toml_string(str(item)) for item in value)
            lines.append(f"{key} = [{rendered}]")
    return "\n".join(lines) + "\n"


def _toml_string(value: str) -> str:
    """A TOML string literal: single-quoted (literal) unless the value contains a single quote."""
    if "'" not in value:
        return f"'{value}'"
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'
